project:
  type: website
  output-dir: docs

website:
  title: "Kaden-Robison-Portfolio"
  navbar:
    left:
      - href: index.html
        text: "Home"
      - href: about.html
        text: "About Me"
      - href: Example-Work.html
        text: "Example Project"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source
